//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TileMap
{
	private uint mWidth;
	public uint Width
	{
		get { return mWidth; }
	}

	private uint mHeight;
	public uint Height
	{
		get { return mHeight; }
	}

	private GameObject[,] mLayerFloor;
	public GameObject[,] LayerFloor
	{
		get { return mLayerFloor; }
	}

	private GameObject[,] mLayerCollide;
	public GameObject[,] LayerCollide
	{
		get { return mLayerCollide; }
	}

	public TileMap (uint width, uint height)
	{
		mWidth = width;
		mHeight = height;

		mLayerFloor = new GameObject[mHeight, mWidth];
		mLayerCollide = new GameObject[mHeight, mWidth];
	}
}
