//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TileFactory
{
	static private TileFactory mInstance;

	static public TileFactory Instance
	{
		get
		{
			if (mInstance == null)
				mInstance = new TileFactory();

			return mInstance;
		}
	}

	public TileFactory ()
	{
	}

	public GameObject CreateTile(char tile_type)
	{
		if (tile_type == '1') {
			return (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Floor") as GameObject);
		} else if (tile_type == '2') {
			return (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Wall") as GameObject);
		} else if (tile_type == '3') {
			return (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Water") as GameObject);
		} else if (tile_type == '4') {
			return (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Sky") as GameObject);
		} else {
			return null;
		}
	}
}

