//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TileMap : MonoBehaviour
{
	public class TileLayer
	{
		private Tile[,] mTiles;
		private TileMap mParent;

		public int Width
		{
			get { return mTiles.GetLength(1); }
		}

		public int Height
		{
			get { return mTiles.GetLength(0); }
		}

		public void Init(TileMap parent, uint width, uint height)
		{
			mParent = parent;
			mTiles = new Tile[height, width];
		}

		public Tile this[int r, int c]
		{
			get { return mTiles[r, c]; }
			set
			{
				value.transform.parent = mParent.transform;
				value.transform.localPosition = new Vector3(c, r, 0);
			}
		}
	}

	private uint mWidth;
	public uint Width
	{
		get { return mWidth; }
	}

	private uint mHeight;
	public uint Height
	{
		get { return mHeight; }
	}

	private TileLayer mLayerFloor;
	public TileLayer LayerFloor
	{
		get { return mLayerFloor; }
	}

	private TileLayer mLayerCollide;
	public TileLayer LayerCollide
	{
		get { return mLayerCollide; }
	}

	public void Init (uint width, uint height)
	{
		mWidth = width;
		mHeight = height;

		mLayerFloor = new TileLayer();
		mLayerFloor.Init(this, width, height);

		mLayerCollide = new TileLayer();
		mLayerCollide.Init(this, width, height);
	}
}
