//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class TileFactory : Singleton<TileFactory>
{
	public Tile CreateTile(char tile_type)
	{
		if (tile_type == '1') {
			var tileObj = (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Floor") as GameObject);
			return tileObj.AddComponent<Tile>();
		} else if (tile_type == '2') {
			var tileObj = (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Wall") as GameObject);
			return tileObj.AddComponent<Tile>();
		} else if (tile_type == '3') {
			var tileObj = (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Water") as GameObject);
			return tileObj.AddComponent<Tile>();
		} else if (tile_type == '4') {
			var tileObj = (GameObject)GameObject.Instantiate (Resources.Load ("Prefabs/Sky") as GameObject);
			return tileObj.AddComponent<Tile>();
		} else {
			return null;
		}
	}
}

